## OpenZz gnu build process scripts.  
## If the 'configure' file is missing
##   run the "autogen.sh" script.

ACLOCAL_AMFLAGS = -I m4
EXTRA_DIST = BUGS ChangeLog autogen.sh build.sh test.sh openzz.spec BUILDING.md docs/CHECKED_PROFILE.md docs/IMPLEMENTAZIONE_PROFILO_CONTROLLATO.md docs/GRAMMATICHE_DINAMICHE_ESTENSIONI_ZZ.md examples/checked/increment.zz examples/checked/modules.zz
EXTRA_DIST += docs/ZZPY_PROTOTIPO.md docs/C_PRIMA_DEL_PREPROCESSORE.md tools/zzpy/base.zz tools/zzpy/zzpy.py \
 examples/zzpy/dynamic.zzpy examples/zzpy/dynamic.py examples/zzpy/syntax/control.zzpy.json
SUBDIRS = src doc testsuite
