/* Generated from tools/zzpy-native/base.zz; checked by tests. */
static const char zzpy_base[] =
"/zlex_set_case_sensitive 1\n"
"/$arg -> pyblock^x :pass\n"
"/stat -> \"pylower\" p_stmt^s :rreturn\n"
"/p_atom -> qstring^x :pass\n"
"/p_atom -> \"__number\" qstring^x :pass\n"
"/p_atom -> \"__string\" qstring^x :pass\n"
"/p_atom -> \"(\" p_expr^x \")\" { /return pycat \"(\" x \")\" }\n"
"/p_atom -> \"{\" \"}\" { /return \"{}\" }\n"
"/p_atom -> \"[\" \"]\" { /return \"[]\" }\n"
"/p_atom -> p_atom^a \"[\" p_expr^i \"]\" { /return pycat a \"[\" pycat i \"]\" \"\" }\n"
"/p_atom -> p_atom^f \"(\" \")\" { /return pycat f \"()\" \"\" }\n"
"/p_atom -> p_atom^f \"(\" p_args^a \")\" { /return pycat f \"(\" pycat a \")\" \"\" }\n"
"/p_args -> p_expr^x :pass\n"
"/p_args -> p_args^a \",\" p_expr^b { /return pycat a \", \" b }\n"
"/p_factor -> p_atom^x :pass\n"
"/p_factor -> \"-\" p_factor^x { /return pycat \"-\" x \"\" }\n"
"/p_term -> p_factor^x :pass\n"
"/p_term -> p_term^a \"*\" p_factor^b { /return pycat a \" * \" b }\n"
"/p_term -> p_term^a \"/\" p_factor^b { /return pycat a \" / \" b }\n"
"/p_term -> p_term^a \"__floordiv\" p_factor^b { /return pycat a \" // \" b }\n"
"/p_term -> p_term^a \"%\" p_factor^b { /return pycat a \" % \" b }\n"
"/p_sum -> p_term^x :pass\n"
"/p_sum -> p_sum^a \"+\" p_term^b { /return pycat a \" + \" b }\n"
"/p_sum -> p_sum^a \"-\" p_term^b { /return pycat a \" - \" b }\n"
"/p_cmp -> p_sum^x :pass\n"
"/p_cmp -> p_sum^a \"==\" p_sum^b { /return pycat a \" == \" b }\n"
"/p_cmp -> p_sum^a \"!=\" p_sum^b { /return pycat a \" != \" b }\n"
"/p_cmp -> p_sum^a \"<\" p_sum^b { /return pycat a \" < \" b }\n"
"/p_cmp -> p_sum^a \">\" p_sum^b { /return pycat a \" > \" b }\n"
"/p_cmp -> p_sum^a \"<=\" p_sum^b { /return pycat a \" <= \" b }\n"
"/p_cmp -> p_sum^a \">=\" p_sum^b { /return pycat a \" >= \" b }\n"
"/p_not -> p_cmp^x :pass\n"
"/p_not -> \"not\" p_not^x { /return pycat \"not \" x \"\" }\n"
"/p_and -> p_not^x :pass\n"
"/p_and -> p_and^a \"and\" p_not^b { /return pycat a \" and \" b }\n"
"/p_expr -> p_and^x :pass\n"
"/p_expr -> p_expr^a \"or\" p_and^b { /return pycat a \" or \" b }\n"
"/p_stmt -> p_sum^a \"=\" p_expr^b \"__NL\" { /return pyassign a b }\n"
"/p_stmt -> p_expr^x \"__NL\" { /return pyline x }\n"
"/p_stmt -> \"pass\" \"__NL\" { /return pyline \"pass\" }\n"
"/p_stmt -> \"if\" p_expr^c \":\" p_suite^b { /return pycompound pycat \"if \" c \":\" b }\n"
"/p_stmt -> \"while\" p_expr^c \":\" p_suite^b { /return pycompound pycat \"while \" c \":\" b }\n"
"/p_stmt -> pyblock^b :pass\n"
"/p_stmts -> p_stmt^s :pass\n"
"/p_leading ->\n"
"/p_leading -> p_leading^$ \"\\n\"\n"
"/p_stmts -> p_stmts^s \"\\n\" :pass\n"
"/p_stmts -> p_stmts^a p_stmt^b { /return pysequence a b }\n"
"/p_suite -> \"__NL\" \"__IN\" p_stmts^s \"__OUT\" :pass\n"
"/p_suite -> \"{\" p_leading^$ p_stmts^s \"}\" { /return s }\n"
"/p_suite -> pyblock^s :pass\n"
"/stat -> \"__emit\" p_stmt^s { pypublish s }\n"
"/stat -> \"import\" \"syntax\" qstring^path { /include path }\n"
"/stat -> \"import\" \"syntax\" { /include \"grammar.zz\" }\n"
"/stat -> \"syntax\" \"zz\" \"{\" $ablock^body \"}\" { /execute body }\n"
;
